nats:
  host: localhost
  port: 4222
  healthcheck_file: /tmp/nats_worker_healthbeat
  loop_sleep_duration: 2
  connect_name: transactions-consumer
  reconnect_time_wait: 5
  connect_timeout: 5
  ping_interval: 120
  max_outstanding_pings: 3

user:
  stream_name: users
  main_subject_name: user
  creation_subject_name: created
  changed_state_subject_name: changed_state

db:
  host: localhost
  port: 5432
  user: transactions_user
  password_file: /run/secrets/transactions_db_password
  database: transactions
  pool:
    min_size: 10
    max_size: 20
    max_inactive_connection_lifetime: 300
    max_connection_lifetime: 3600
    timeout: 20
